# S: Build Lifecycle
install:
  - git pull git@github.com:JUTSSAM/jutssam.github.io.git
after_script:
  - cd jutssam.github.io/public
  - git init
  - git config user.name "jutssam"
  - git config user.email "ybj948244086@126.com"
  - git add .
  - git commit -m "Update docs"
  - git push -f "https://{REF}" master:gh-pages
env:
  global:
  - REF=github.com/JUTSSAM/jutssam.github.io
# E: Build LifeCycle
