baseURL = "http://j.noloss.cn/"
publishDir = "docs"
languageCode = "zh-cn"
title = "Bonjour.Yang"
theme = "angels-ladder"
comments = true
disqusShortname = "bonjour-yang"

[Params]
subtitle = "务必使同志们继续地保持谦虚谨慎、不骄不躁的作风。务必使同志们继续地保持艰苦奋斗的作风。"
github = "https://gitee.com/jutssam"
analytics = "UA-121684556-1"
